'use client'

import { useRouter } from 'next/navigation'
import { useEffect } from 'react'

export default function AdminPage() {
  const router = useRouter()

  useEffect(() => {
    // Redirect to the static admin page generated by TinaCMS
    window.location.href = '/admin/index.html'
  }, [])

  return (
    <div className="min-h-screen flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-2xl font-bold mb-4">Redirecting to TinaCMS Admin...</h1>
        <p className="text-gray-600">If you're not redirected automatically, <a href="/admin/index.html" className="text-blue-500 hover:underline">click here</a></p>
      </div>
    </div>
  )
} 