AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal test template'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

Resources:
  TestSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'hh-bot-test-sg'
      GroupDescription: 'Test security group'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/8
          Description: 'Test rule'

Outputs:
  SecurityGroupId:
    Description: 'Test Security Group ID'
    Value: !Ref TestSecurityGroup
